### ISSUE TITLE
Generate learned geometry

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [vislearn/dsacstar#10]
HI!

Could you please clearify how to generate learned geometry? i've tried to run test.py saving 
scene_coordinates = scene_coordinates.cpu()
cv2.imwrite(str(file),scene_coordinates.permute([0,2,3,1]).numpy()[0])
So I got network predictions, but it is not clear how to generate a point cloud from them. I took all these images and reshaped them to the (N, 3) , but when I visualize them I get following:
![image](https://user-images.githubusercontent.com/22734034/126347384-e19395ee-f6be-4e42-aea0-561b3f4cef46.png)

**Comment by ebrach** [comment]
Hi,
I usually just write the scene coordinate predictions into a txt file, with one line per 3D point in the form X Y Z R G B. XYZ is comes from the network, RGB comes from the input image. Just down-size the input image to the same dimensions as the network prediction, and read out colors at the same positions as the predicted 3D point.

These text files can be opened with tools like MeshLab or CloudCompare. You can run Poisson reconstruction on top to get a (crude) mesh.

Hope that helps,
Eric

**Comment by YaroslavShchekaturov** [comment]
Hi Eric!

Thank you very much for you help!

Best,
Yaroslav
