### ISSUE TITLE
Problem with the result about cambridge datasets

### ISSUE THREAD

**Issue by aruba01** [vislearn/dsacstar#14]
I test the pre-trained network  on cambridge datasets. The results of OldHospital, ShopFacade and StMarysChurch are obviously deviated from the normal value, while the results of KingsCollege and GreatCourt are normal. I guess that the pre-trained network do not correspond to dataset. The following is the screenshot of ShopFacade:
![4~BMA27B 5{ V16V RT% @D](https://user-images.githubusercontent.com/47864285/136445820-a4971d63-64ab-495f-8621-95206282d6fc.png)

**Comment by ebrach** [comment]
That is very strange behaviour that I have not seen before. Having a mismatch between the network and the scene might be one explanation. May I ask how you call exactly to get those results?

**Comment by ebrach** [comment]
I can reproduce your results. There is a mixup in the filenames of the pre-trained models. The following combinations yield the correct results:
```
python test.py Cambridge_OldHospital models/rgbm/cambridge/Cambridge_ShopFacade.net --mode 1
python test.py Cambridge_ShopFacade models/rgbm/cambridge/Cambridge_StMarysChurch.net --mode 1
python test.py Cambridge_StMarysChurch models/rgbm/cambridge/Cambridge_OldHospital.net --mode 1
```
I will try to trigger an update of the models data package. Thanks for brining it up!

**Comment by ebrach** [comment]
I updated the data package of pre-trained models to fix the naming error. Everything should work now.
