### ISSUE TITLE
visualize the scene coordinate

### ISSUE THREAD

**Issue by qzhai** [vislearn/dsacstar#15]
Dear,

Could you help to release the scripts to visualize the scene coordinate and camera trajectory in the DSAC* paper?

Thank you so much.

Best,
Qiang

**Comment by ebrach** [comment]
Hi Qiang,

sorry but this is not possible. That was custom code that was not ready for publication when I changed jobs. I do not have access anymore.

But visualisation with custom tools like CloudCompare is rather easy if you write out scene coordinates (predicted or ground truth) and camera positions (estimated or ground truth) as coloured point clouds. The results will look very similar to what is in the paper. 

You can run Poisson reconstruction on the scene point clouds to get a textured mesh, too.

Best,
Eric
