### ISSUE TITLE
Problem with data downloading again

### ISSUE THREAD

**Issue by Chicolor** [vislearn/dsacstar#21]
I can't download 7scenes_rendered_depth and 12scenes_rendered_depth from https://heidata.uni-heidelberg.de/. I have tried several times but each time I failed to download them halfway. Is there other methods in which I can get access to the data? Sorry to bother you. I would appreciate your help.

**Comment by ebrach** [comment]
Sorry to hear that you have trouble downloading that data. Unfortunately, it is not available anywhere else. I just downloaded it successfully, so my only advice is to be patient, unfortunately.
