### ISSUE TITLE
The impact of number of images and size of scene 

### ISSUE THREAD

**Issue by MACILLAS** [vislearn/dsacstar#28]
Thank you authors for this amazing work!

I am wondering what your thoughts are about the relationship between the number of images and the size of a scene? For example, I have a tall structure about 5m^3, which is the subject of my scene, and about 100 images (with poses)... In your opinion do I need more training images? 

Many Thanks, 

MACILLAS

**Comment by ebrach** [comment]
Hi MACILLAS,

It is hard to say without seeing the images, but in general DSAC* can cope with few training images as long as they cover the scene, and there is sufficient image overlap between views. I think you just have to try it. And if the results are bad, too few mapping images could be one potential reason.

Best,
Eric
