### ISSUE TITLE
Question about calibration files

### ISSUE THREAD

**Issue by shenyehui** [vislearn/dsacstar#29]
Dear author, may I ask how to convert the content of the calibration file into the form [fx 0 cx 0] [0 fy cy 0] [0 0 1 0]? For example, is 740.8688250209896 in seq2_frame00001.txt converted to [740.8688 0 1 0] [0 7408688 1 0] [0 0 1 0]? However, each frame has its own calibration file. Does this indicate that the intrinsic and extrinsic parameters for each frame are different?

**Comment by ebrach** [comment]
Hi. The calibration files contain the focal length of each image. Here is the code to convert that value to a full calibration matrix: 
https://github.com/vislearn/dsacstar/blob/25accc6ae7b3a446ca86ce2487fbfd3daa0a640a/train_init.py#L127-L134

The code assumes that fx and fy are shared, and that the principal point is in the center of the frame.

Whether the intrinsics (i.e. the focal length) are shared across frames or not depends on the dataset. The code assumes that a separate focal length value is given per frame. If the dataset comes with shared intrinsics, the calibration files would all contain the same value.

Best,
Eric

**Comment by shenyehui** [comment]
> Hi. The calibration files contain the focal length of each image. Here is the code to convert that value to a full calibration matrix:
> 
> https://github.com/vislearn/dsacstar/blob/25accc6ae7b3a446ca86ce2487fbfd3daa0a640a/train_init.py#L127-L134
> 
> The code assumes that fx and fy are shared, and that the principal point is in the center of the frame.
> 
> Whether the intrinsics (i.e. the focal length) are shared across frames or not depends on the dataset. The code assumes that a separate focal length value is given per frame. If the dataset comes with shared intrinsics, the calibration files would all contain the same value.
> 
> Best, Eric

Thank you for your response! May I ask why there is a significant difference in focal_length in each epoch? I have examined the code in dataset.py and found that there are only some scaling operations applied to focal_length. In the calibration folder, each focal length is around 740, and even with some scaling operations, there shouldn't be such a large difference.
