### ISSUE TITLE
Do I need to compile and install opencv with CUDA support for DSAC* to work?

### ISSUE THREAD

**Issue by chudur-budur** [vislearn/dsacstar#3]
The README says, I need to have opencv (3.4.2). Do I need to compile and install opencv (3.4.2) with CUDA enabled? 

Like the process described here?

https://www.pyimagesearch.com/2016/07/11/compiling-opencv-with-cuda-support/

**Comment by ebrach** [comment]
CUDA should not be necessary for OpenCV.

**Comment by chudur-budur** [comment]
Okay got it, thanks!!
