### ISSUE TITLE
 import dsacstar：ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by lwhhhh13** [vislearn/dsacstar#32]
Hello, it seems that my C++ extension is not compiling successfully. I have already installed setup.py, and it shows "Finished processing dependencies for dsacstar==0.0.0", indicating that the module seems to have been compiled correctly and I can import dsacstar. However, why do I still get an error when I run train_e2e_.py: "ImportError: DLL load failed: The specified module could not be found."? Can you help me with this?

**Comment by ebrach** [comment]
Hi! Looks like you are trying to run DSAC* on Windows. This is something we never tried, and we cannot provide support for, unfortunately.

**Comment by ebrach** [comment]
NG-RANSAC uses code that is similar to that of DSAC*, and someone managed to get NG-RANSAC working on Windows. They kindly documented their approach in the NG-RANSAC repository. Maybe that is useful to you: https://github.com/vislearn/ngransac/issues/21

**Comment by lwhhhh13** [comment]
> NG-RANSAC 使用的代码与 DSAC* 的代码类似，有人设法让 NG-RANSAC 在 Windows 上运行。他们亲切地在NG-RANSAC存储库中记录了他们的方法。也许这对你有用：[vislearn/ngransac#21](https://github.com/vislearn/ngransac/issues/21)
Thank you for your reply，I‘m going to learn about it.
