### ISSUE TITLE
Compatibility Issue with Updated Environment Versions

### ISSUE THREAD

**Issue by JingruiYu** [vislearn/dsacstar#33]
Hello,

First of all, I would like to express my appreciation for the dsac* project. It looks like a fantastic tool, and I am eager to try it out. However, I am facing some compatibility issues due to the limitations of my GPU hardware.

Currently, I am using the following versions:
- PyTorch: 1.12.0
- CUDA: 11.8
- OpenCV: 4.10

When I attempt to run the test code, I encounter the following error:

```
File "test.py", line 6, in <module>
    import dsacstar
ImportError: /miniconda3/envs/t16c102/lib/python3.8/site-packages/dsacstar-0.0.0-py3.8-linux-x86_64.egg/dsacstar.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2cv6String8allocateEm
```

I understand that this issue is related to the OpenCV version. Could you please let me know if there is a possibility of supporting these updated environment versions? Your assistance would be greatly appreciated.

Thank you for your time and support.

**Comment by ebrach** [comment]
Hi! The code can be adjusted for OpenCV 4.x but it requires some changes. We did this for [ACE](https://github.com/nianticlabs/ace) which also uses the DSAC* C++ extension - but the ACE version only supports the RGB forward function (i.e. no end-to-end training and no RGB-D mode). Maybe it is still useful as an example of how to port from OpenCV 3.x to 4.x.

Best,
Eric
