### ISSUE TITLE
What does it mean by "opencv (3.4.2)"?

### ISSUE THREAD

**Issue by chudur-budur** [vislearn/dsacstar#4]
Which one is it?

opencv 3.4.2 (opencv.org): https://github.com/opencv/opencv/releases/tag/3.4.2
opencv-python 3.4.2.16 (pypi.org): https://pypi.org/project/opencv-python/3.4.2.16/#history
opencv 3.4.2 (anaconda.org): https://anaconda.org/conda-forge/opencv

**Comment by ebrach** [comment]
All of these should work. Installing via conda is probably the most convenient solution and should work well with the C++ setup script.

**Comment by chudur-budur** [comment]
Okay, got it. Thanks!
