### ISSUE TITLE
Getting Runtime Error when running on Windows 10

### ISSUE THREAD

**Issue by RameshKamath** [vislearn/dsacstar#8]
I was able to build the code to windows on.

* conda python 3.7.10
* MSVC c++ compiler
* requirements from README.md

I got this Error when running the train_init.py on chess dataset.

i used :
`python .\train_init.py 7scenes_chess chess --mode 0 `

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

i think this is problem from not linking openmp with -fopenmp flag or some other error in windows.

**Comment by ebrach** [comment]
Sorry, but I cannot provide support for Windows at the moment.

**Comment by YaroslavShchekaturov** [comment]
I have solved that by adding this lines 
![image](https://user-images.githubusercontent.com/22734034/124186977-c137bc80-dac5-11eb-942d-8b5cabf163a7.png)

![image](https://user-images.githubusercontent.com/22734034/124186942-b4b36400-dac5-11eb-840a-abff1dcb857f.png)

**Comment by ebrach** [comment]
Awesome, thanks for following up on this!
