### ISSUE TITLE
Dataset preparation (camera pose)

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [vislearn/dsacstar#9]
HI! 

Am I right that if I want to use camera pose extracted from the blender ( obj.matrix_world) I need to multiply it by diag(1 -1 -1 1) to follow the OpenCV convention?

Thank you!

**Comment by ebrach** [comment]
I'm not sure what convention Blender uses, but you are right about DSAC* using the OpenCV convention. If Blender uses the OpenGL convention, you might have to flip twice: Flip second and third column, then flip second and third row. (Result of multiplying `diag(1 -1 -1 1) ` from left and from right.)

Let me know whether you solved the issue.

Best,
Eric

**Comment by YaroslavShchekaturov** [comment]
Thank you! 

I solved this issue when I simply saw this picture.
![image](https://user-images.githubusercontent.com/22734034/124459880-558c7280-dd97-11eb-8c46-a5c4f9cfc37e.png)

So I did it like this 
![image](https://user-images.githubusercontent.com/22734034/124460391-01ce5900-dd98-11eb-9f96-d2020cb2e1b2.png)

Best, 
Yaroslav
